### ISSUE TITLE
добавить удобное время

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/newgen#20]
@Amfitorin @anna-geo @wr6bit @aumkara @bitlomanka @EliteEugene @klylex @lARKHIPl @oorjoock @stoyat @timurkashapov 

в файлик the_meeting.txt

**Comment by Amfitorin** [comment]
Added my time on the_meeting.txt

**Comment by anna-geo** [comment]
Done

**Comment by ghost** [comment]
I added

**Comment by GSuvorov** [comment]
done
